"""empty message

Revision ID: 168c4168ef64
Revises: f35533c7a20f
Create Date: 2021-10-18 11:12:38.603682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168c4168ef64'
down_revision = 'f35533c7a20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
