"""empty message

Revision ID: f35533c7a20f
Revises: 0c4d40fbcb9e
Create Date: 2021-10-18 08:21:34.449225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35533c7a20f'
down_revision = '0c4d40fbcb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citys', 'ddd',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'citys', ['ddd'])
    op.create_unique_constraint(None, 'countrys', ['sigla'])
    op.create_unique_constraint(None, 'states', ['sigla'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_constraint(None, 'countrys', type_='unique')
    op.drop_constraint(None, 'citys', type_='unique')
    op.alter_column('citys', 'ddd',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
